services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./Backend/src:/app/src
    environment:
      - NODE_ENV=development
    networks:
      - ultrasound
    depends_on:
      - db
  db:
    image: postgres:17.2-alpine3.21
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - ultrasound

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80" 
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro 
    depends_on:
      - frontend
      - backend
    networks:
      - ultrasound

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - ultrasound
    depends_on:
      - backend


volumes:
  db-data: 
networks:
  ultrasound:
    driver: bridge