services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./Backend/src:/app/src
    environment:
      - NODE_ENV=development
    networks:
      - ultrasound
    depends_on:
      - db
  db:
    image: postgres:17.2-alpine3.21
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - ultrasound

volumes:
  db-data:  # Définition du volume utilisé par la base de données

networks:
  ultrasound:
    driver: bridge